version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/rust
    command: cargo watch -x run
    environment:
      USER: $USER
    working_dir: /rust
